Models/AgentView.cs
namespace MossadAPI.Models
{
    public class AgentView
    {
        public int ID { get; set; }
        public string PhotoUrl { get; set; }
        public string Nickname { get; set; }
        public StatusAgent? StatusAgent { get; set; }
        public string Location { get; set; }
        public int Kills { get; set; } = 0;
        public int? MissionID { get; set; }
        public double? TimeLeft { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace MossadMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MossadView.cs
namespace MossadMVC.Models
{
    public class MossadView
    {
        public int TotalAgents { get; set; }
        public int TotalAgentsActivate { get; set; }
        public int TotalTargets { get; set; }
        public int TotalTargetsDead { get; set; }
        public int TotalMissions { get; set; }
        public int TotalMissionsActivate { get; set; }
        public double AgentsToTargets { get; set; }
        public double SAgentsToTargets { get; set; }
    }
}

Models/StatusAgent.cs
namespace MossadAPI.Models
{
    public enum StatusAgent
    {
        Dormant,
        InActivity
    }
}

Models/StatusTarget.cs
namespace MossadMVC.Models
{
    public enum StatusTarget
    {
        Live,
        Eliminated
    }
}

Models/SuggestionView.cs
namespace MossadMVC.Models
{
    public class SuggestionView
    {
        public int MissionID { get; set; }
        public string AgentNickname { get; set; }
        public string AgentLocation { get; set; }
        public string TargetName { get; set; }
        public string TargetPosition { get; set; }
        public string TargetLocation { get; set; }
        public double Distance { get; set; }
        public double? TimeLeft { get; set; }
    }
}

Models/TargetView.cs
namespace MossadMVC.Models
{
    public class TargetView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string PhotoUrl { get; set; }
        public string Location { get; set; }
        public StatusTarget StatusTarget { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MossadAPI.Models;
using MossadMVC.Models;
using Newtonsoft.Json;
using System.Diagnostics;

namespace MossadMVC.Controllers
{
    public class HomeController : Controller
    {

        private readonly HttpClient _httpClient;
        public HomeController()
        {
            _httpClient = new HttpClient();
        }

        public async Task<IActionResult> Mossad()
        {
            var result = await _httpClient.GetStringAsync($"http://localhost:5059/View/mossad");
            MossadView? mossad = JsonConvert.DeserializeObject<MossadView>(result);
            return View(mossad);
        }

        public async Task<IActionResult> Targets()
        {
            var result = await _httpClient.GetStringAsync($"http://localhost:5059/View/Targets");
            List<TargetView>? targets = JsonConvert.DeserializeObject<List<TargetView>>(result);
            return View(targets);
        }

        public async Task<IActionResult> Agents()
        {
            var result = await _httpClient.GetStringAsync($"http://localhost:5059/View/Agents");
            List<AgentView>? agents = JsonConvert.DeserializeObject<List<AgentView>>(result);
            return View(agents);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SuggestionsController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;

using MossadMVC.Models;

namespace MossadMVC.Controllers
{
    public class SuggestionsController : Controller
    {
        private readonly HttpClient _httpClient;
        public SuggestionsController()
        {
            _httpClient = new HttpClient();
        }

        public async Task<IActionResult> Index()
        {
            var result = await _httpClient.GetStringAsync("http://localhost:5059/View/suggestionsMissions");
            List<SuggestionView>? suggestions = JsonConvert.DeserializeObject<List<SuggestionView>>(result);
            return View(suggestions);
        }

        public async Task<IActionResult> Details(int id)
        {
            var result = await _httpClient.GetStringAsync($"http://localhost:5059/View/suggestionsMissions/{id}");
            if (result == null) { return RedirectToAction("Index"); }
            SuggestionView? suggestions = JsonConvert.DeserializeObject<SuggestionView>(result);
            return View(suggestions);
        }

        public async Task<IActionResult> PutStatus(int id)
        {
            await _httpClient.PutAsJsonAsync($"http://localhost:5059/Missions/{id}", "{ “status”: “Assigned” }");
            return RedirectToAction("Index");
        }
    }
}

Views/Home/Agents.cshtml
@model IEnumerable<MossadAPI.Models.AgentView>

@{
    ViewData["Title"] = "Agents";
}

<h1>Agents</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhotoUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nickname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StatusAgent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kills)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MissionID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeLeft)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhotoUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nickname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusAgent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kills)
            </td>
            <td>
                @if (item.MissionID != null) 
                {
                    <a asp-controller="Suggestions" asp-action="Details" asp-route-id="@item.MissionID">To Mission...</a>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeLeft)
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/Mossad.cshtml
@model MossadMVC.Models.MossadView

@{
    ViewData["Title"] = "Mossad";
}

<h1>Mossad</h1>

<div>
    <h4>MossadView</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalAgents)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalAgents)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalAgentsActivate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalAgentsActivate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalTargets)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalTargets)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalTargetsDead)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalTargetsDead)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalMissions)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalMissions)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalMissionsActivate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalMissionsActivate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AgentsToTargets)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AgentsToTargets)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SAgentsToTargets)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SAgentsToTargets)
        </dd>
    </dl>
</div>

Views/Home/Targets.cshtml
@model IEnumerable<MossadMVC.Models.TargetView>

@{
    ViewData["Title"] = "Targets";
}

<h1>Targets</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhotoUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StatusTarget)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhotoUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusTarget)
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MossadMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MossadMVC.styles.css" asp-append-version="true" />  
    <meta http-equiv="refresh" content="3">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MossadMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Suggestions" asp-action="Index">Suggestions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Mossad">General</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Targets">Targets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Agents">Agents</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MossadMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Suggestions/Details.cshtml
@model MossadMVC.Models.SuggestionView

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SuggestionView</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MissionID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MissionID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AgentNickname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AgentNickname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AgentLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AgentLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TargetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TargetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TargetPosition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TargetPosition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TargetLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TargetLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Distance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Distance)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeLeft)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeLeft)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="PutStatus" asp-route-id="@Model.MissionID">Exepte Mission</a> |
    <a asp-action="Index">Back to Seggestions</a>
</div>

Views/Suggestions/Index.cshtml
@model IEnumerable<MossadMVC.Models.SuggestionView>

@{
    ViewData["Title"] = "Index";
}

<h1>Suggestion</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MissionID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AgentNickname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AgentLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TargetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TargetPosition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TargetLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Distance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeLeft)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MissionID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AgentNickname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AgentLocation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TargetName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TargetPosition)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TargetLocation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Distance)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimeLeft)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.MissionID })
                </td>
            </tr>
        }
    </tbody>
</table>